"""
Preset configurations for Detect Bot
"""

from lib.constants import (
    DEFAULT_ALLOW_MIME_PREFIXES,
    DEFAULT_ALLOW_EXTS,
    DEFAULT_CONTENT_EXTS,
    DEFAULT_PII_EXTS,
)

PRESETS = {
    "안전 모드": {
        "purpose": "운영 점검",
        "server_type": "nginx",
        "newer_than_h": 24,
        "max_depth": 8,
        "workers": 4,
        "follow_symlink": False,
        "max_size_mb": 100,
        "hash_enabled": False,
        "allow_mime_prefixes": DEFAULT_ALLOW_MIME_PREFIXES,
        "allow_exts": DEFAULT_ALLOW_EXTS,
        "content_scan": False,
        "content_max_bytes": 65536,
        "content_max_size_kb": 1024,
        "content_exts": DEFAULT_CONTENT_EXTS,
        "pii_scan": False,
        "pii_max_bytes": 65536,
        "pii_max_size_kb": 256,
        "pii_max_matches": 5,
        "pii_exts": DEFAULT_PII_EXTS,
        "pii_mask": True,
        "pii_store_sample": True,
        "pii_context_keywords": True,
        "enable_rules": [],
        "disable_rules": [],
        "excludes": ["/var/cache", "/tmp"],
        "output_path": "/tmp/report.json",
        "kafka_enabled": False,
        "kafka_brokers": "",
        "kafka_topic": "",
        "kafka_client_id": "detectbot",
        "kafka_tls": False,
        "kafka_sasl_enabled": False,
        "kafka_username": "",
        "kafka_password_env": "",
        "kafka_mask_sensitive": True,
    },
    "균형 모드": {
        "purpose": "운영 점검",
        "server_type": "nginx",
        "newer_than_h": 24,
        "max_depth": 10,
        "workers": 4,
        "follow_symlink": False,
        "max_size_mb": 100,
        "hash_enabled": False,
        "allow_mime_prefixes": DEFAULT_ALLOW_MIME_PREFIXES,
        "allow_exts": DEFAULT_ALLOW_EXTS,
        "content_scan": True,
        "content_max_bytes": 65536,
        "content_max_size_kb": 1024,
        "content_exts": DEFAULT_CONTENT_EXTS,
        "pii_scan": False,
        "pii_max_bytes": 65536,
        "pii_max_size_kb": 256,
        "pii_max_matches": 5,
        "pii_exts": DEFAULT_PII_EXTS,
        "pii_mask": True,
        "pii_store_sample": True,
        "pii_context_keywords": True,
        "enable_rules": [],
        "disable_rules": [],
        "excludes": ["/var/cache", "/tmp", "node_modules"],
        "output_path": "/tmp/report.json",
        "kafka_enabled": False,
        "kafka_brokers": "",
        "kafka_topic": "",
        "kafka_client_id": "detectbot",
        "kafka_tls": False,
        "kafka_sasl_enabled": False,
        "kafka_username": "",
        "kafka_password_env": "",
        "kafka_mask_sensitive": True,
    },
    "정밀 모드": {
        "purpose": "정기 점검",
        "server_type": "nginx",
        "newer_than_h": 72,
        "max_depth": 12,
        "workers": 6,
        "follow_symlink": False,
        "max_size_mb": 100,
        "hash_enabled": True,
        "allow_mime_prefixes": DEFAULT_ALLOW_MIME_PREFIXES,
        "allow_exts": DEFAULT_ALLOW_EXTS,
        "content_scan": True,
        "content_max_bytes": 65536,
        "content_max_size_kb": 1024,
        "content_exts": DEFAULT_CONTENT_EXTS,
        "pii_scan": True,
        "pii_max_bytes": 65536,
        "pii_max_size_kb": 256,
        "pii_max_matches": 5,
        "pii_exts": DEFAULT_PII_EXTS,
        "pii_mask": True,
        "pii_store_sample": True,
        "pii_context_keywords": True,
        "enable_rules": [],
        "disable_rules": [],
        "excludes": ["/var/cache"],
        "output_path": "/tmp/report.json",
        "kafka_enabled": False,
        "kafka_brokers": "",
        "kafka_topic": "",
        "kafka_client_id": "detectbot",
        "kafka_tls": False,
        "kafka_sasl_enabled": False,
        "kafka_username": "",
        "kafka_password_env": "",
        "kafka_mask_sensitive": True,
    },
}
